"""Curated skill and phrase lexicon used by CareerLens AI.

The lexicon is intentionally explicit so matching stays explainable.
Each skill has a canonical name, a category, and optional aliases.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SkillTerm:
    name: str
    category: str
    aliases: tuple[str, ...] = ()


SKILL_TERMS: tuple[SkillTerm, ...] = (
    # Languages
    SkillTerm("Python", "language", ("python3", "py")),
    SkillTerm("JavaScript", "language", ("js", "ecmascript", "es6")),
    SkillTerm("TypeScript", "language", ("ts",)),
    SkillTerm("Java", "language"),
    SkillTerm("C#", "language", ("csharp", "c sharp")),
    SkillTerm("C++", "language", ("cpp", "c plus plus")),
    SkillTerm("Go", "language", ("golang", "go lang")),
    SkillTerm("Rust", "language"),
    SkillTerm("Ruby", "language"),
    SkillTerm("PHP", "language"),
    SkillTerm("Swift", "language"),
    SkillTerm("Kotlin", "language"),
    SkillTerm("Scala", "language"),
    SkillTerm("R", "language", ("r language", "r programming")),
    SkillTerm("SQL", "language"),
    SkillTerm("HTML", "language", ("html5",)),
    SkillTerm("CSS", "language", ("css3",)),
    SkillTerm("Bash", "language", ("shell scripting", "bash scripting")),
    # Frontend
    SkillTerm("React", "frontend", ("react.js", "reactjs")),
    SkillTerm("Angular", "frontend", ("angular.js", "angularjs")),
    SkillTerm("Vue", "frontend", ("vue.js", "vuejs")),
    SkillTerm("Next.js", "frontend", ("nextjs", "next js")),
    SkillTerm("Svelte", "frontend"),
    SkillTerm("Redux", "frontend"),
    SkillTerm("Tailwind CSS", "frontend", ("tailwind", "tailwindcss")),
    SkillTerm("Bootstrap", "frontend"),
    SkillTerm("Sass", "frontend", ("scss",)),
    SkillTerm("Vite", "frontend"),
    SkillTerm("Webpack", "frontend"),
    SkillTerm("Responsive Design", "frontend", ("responsive layouts", "mobile friendly")),
    SkillTerm("Accessibility", "frontend", ("a11y", "wcag")),
    # Backend
    SkillTerm("Node.js", "backend", ("nodejs", "node js", "node")),
    SkillTerm("Express", "backend", ("express.js", "expressjs")),
    SkillTerm("FastAPI", "backend"),
    SkillTerm("Django", "backend"),
    SkillTerm("Flask", "backend"),
    SkillTerm("SQLAlchemy", "backend"),
    SkillTerm("AsyncIO", "backend", ("asyncio",)),
    SkillTerm("OAuth", "backend", ("oauth2",)),
    SkillTerm("JWT", "backend"),
    SkillTerm("Streamlit", "backend"),
    SkillTerm("Spring Boot", "backend", ("springboot", "spring")),
    SkillTerm("ASP.NET", "backend", ("aspnet", ".net", "dotnet")),
    SkillTerm("REST APIs", "backend", ("rest api", "restful", "rest apis", "api development")),
    SkillTerm("GraphQL", "backend"),
    SkillTerm("gRPC", "backend"),
    SkillTerm("Microservices", "backend"),
    # Databases
    SkillTerm("PostgreSQL", "database", ("postgres", "psql")),
    SkillTerm("MySQL", "database"),
    SkillTerm("Microsoft SQL Server", "database", ("sql server", "mssql", "tsql")),
    SkillTerm("SQLite", "database"),
    SkillTerm("MongoDB", "database", ("mongo",)),
    SkillTerm("Redis", "database"),
    SkillTerm("Elasticsearch", "database", ("elastic search",)),
    SkillTerm("DynamoDB", "database"),
    SkillTerm("Oracle", "database"),
    # Cloud / DevOps
    SkillTerm("AWS", "cloud", ("amazon web services",)),
    SkillTerm("Azure", "cloud", ("microsoft azure",)),
    SkillTerm("Google Cloud", "cloud", ("gcp", "google cloud platform")),
    SkillTerm("Docker", "devops"),
    SkillTerm("Kubernetes", "devops", ("k8s",)),
    SkillTerm("CI/CD", "devops", ("continuous integration", "continuous delivery", "github actions")),
    SkillTerm("Terraform", "devops"),
    SkillTerm("Linux", "devops"),
    SkillTerm("Nginx", "devops"),
    # Data / ML / AI
    SkillTerm("Machine Learning", "data", ("ml",)),
    SkillTerm("Deep Learning", "data"),
    SkillTerm("Data Science", "data"),
    SkillTerm("NLP", "data", ("natural language processing",)),
    SkillTerm("Generative AI", "data", ("genai", "llm", "large language models")),
    SkillTerm("RAG", "data", ("retrieval augmented generation",)),
    SkillTerm("Agentic AI", "data", ("ai agents", "multi-agent", "multi-agent systems")),
    SkillTerm("PyTorch", "data"),
    SkillTerm("Amazon S3", "cloud", ("s3", "aws s3")),
    SkillTerm("LangChain", "data"),
    SkillTerm("LangGraph", "data"),
    SkillTerm("MCP", "data", ("model context protocol", "mcp server")),
    SkillTerm("ChromaDB", "data", ("chroma", "vector store")),
    SkillTerm("Hugging Face", "data", ("huggingface", "transformers")),
    SkillTerm("OpenCV", "data"),
    SkillTerm("BERT", "data"),
    SkillTerm("ETL", "data", ("etl pipelines", "etl pipeline")),
    SkillTerm("TensorFlow", "data"),
    SkillTerm("scikit-learn", "data", ("sklearn", "scikit learn")),
    SkillTerm("Pandas", "data"),
    SkillTerm("NumPy", "data", ("numpy",)),
    SkillTerm("Apache Spark", "data", ("pyspark", "spark")),
    SkillTerm("Airflow", "data"),
    SkillTerm("Power BI", "data", ("powerbi",)),
    SkillTerm("Tableau", "data"),
    SkillTerm("Statistics", "data"),
    # Mobile
    SkillTerm("React Native", "mobile"),
    SkillTerm("Flutter", "mobile"),
    SkillTerm("iOS", "mobile"),
    SkillTerm("Android", "mobile"),
    # Tools / practices
    SkillTerm("Git", "tools"),
    SkillTerm("GitHub", "tools"),
    SkillTerm("GitLab", "tools"),
    SkillTerm("Jira", "tools"),
    SkillTerm("Postman", "tools"),
    SkillTerm("Figma", "tools"),
    SkillTerm("Jest", "testing"),
    SkillTerm("Playwright", "testing"),
    SkillTerm("Cypress", "testing"),
    SkillTerm("PyTest", "testing", ("pytest",)),
    SkillTerm("JUnit", "testing"),
    SkillTerm("Unit Testing", "testing", ("unit tests", "automated tests")),
    SkillTerm("Integration Testing", "testing", ("integration tests",)),
    SkillTerm("Agile", "practice", ("scrum", "sprint planning")),
    SkillTerm("Code Review", "practice", ("pull requests", "pr review")),
    SkillTerm("System Design", "practice"),
    SkillTerm("Object-Oriented Programming", "practice", ("oop",)),
    # Soft skills
    SkillTerm("Communication", "soft", ("written communication", "verbal communication")),
    SkillTerm("Collaboration", "soft", ("cross-functional", "teamwork")),
    SkillTerm("Leadership", "soft"),
    SkillTerm("Mentoring", "soft", ("mentorship",)),
    SkillTerm("Problem Solving", "soft", ("problem-solving",)),
    SkillTerm("Ownership", "soft"),
    SkillTerm("Documentation", "soft", ("technical writing",)),
    SkillTerm("On-call", "soft", ("on call", "pager")),
)

DEGREE_PHRASES = (
    "bachelor",
    "bachelors",
    "b.s",
    "bs ",
    "b.sc",
    "master",
    "masters",
    "m.s",
    "msc",
    "mba",
    "phd",
    "doctorate",
    "associate degree",
    "computer science",
    "software engineering",
    "information technology",
    "information systems",
    "data science",
    "electrical engineering",
)

EXPERIENCE_CUES = (
    "developed",
    "built",
    "designed",
    "implemented",
    "led",
    "owned",
    "launched",
    "improved",
    "reduced",
    "increased",
    "migrated",
    "architected",
    "collaborated",
    "maintained",
    "shipped",
    "optimized",
    "automated",
    "mentored",
    "reviewed",
    "deployed",
)

SENIORITY_TERMS = (
    "intern",
    "junior",
    "associate",
    "mid-level",
    "senior",
    "staff",
    "principal",
    "lead",
    "manager",
)

STOPWORDS = {
    "a",
    "an",
    "the",
    "and",
    "or",
    "but",
    "if",
    "then",
    "else",
    "when",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "once",
    "here",
    "there",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now",
    "of",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "do",
    "does",
    "did",
    "this",
    "that",
    "these",
    "those",
    "you",
    "your",
    "we",
    "our",
    "they",
    "their",
    "it",
    "its",
    "as",
    "role",
    "team",
    "work",
    "working",
    "using",
    "used",
    "use",
    "ability",
    "strong",
    "including",
    "across",
    "within",
    "help",
    "also",
    "well",
    "please",
    "able",
    "must",
    "etc",
}
